config/routes.rb
Rails.application.routes.draw do
  resources :peripherals
  resources :employees
  resources :employees_peripherals

   root 'employees_peripherals#index'
 

end

app/models/employee.rb
class Employee < ActiveRecord::Base
 has_many :peripherals, :through => :employees_peripherals
 has_many :employees_peripherals, :dependent => :destroy
 validates :name, presence:true
end

app/models/employees_peripheral.rb
class EmployeesPeripheral < ActiveRecord::Base
  belongs_to :employee
  belongs_to :peripheral
end

app/models/peripheral.rb
class Peripheral < ActiveRecord::Base
  has_many :employees, :through => :employees_peripheral
  has_many :employees_peripheral, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)
    @employee.attributes = {'peripheral_ids' => []}.merge(params[:employee] || {})
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :peripheral_ids =>[])
    end
end

app/controllers/employees_peripherals_controller.rb
class EmployeesPeripheralsController < ApplicationController

  def index
  end

  def create  
  end

  def new
  end

end

app/controllers/peripherals_controller.rb
class PeripheralsController < ApplicationController
  before_action :set_peripheral, only: [:show, :edit, :update, :destroy]

  # GET /peripherals
  # GET /peripherals.json
  def index
    @peripherals = Peripheral.all
  end

  # GET /peripherals/1
  # GET /peripherals/1.json
  def show
  end

  # GET /peripherals/new
  def new
    @peripheral = Peripheral.new
  end

  # GET /peripherals/1/edit
  def edit
  end

  # POST /peripherals
  # POST /peripherals.json
  def create
    @peripheral = Peripheral.new(peripheral_params)

    respond_to do |format|
      if @peripheral.save
        format.html { redirect_to @peripheral, notice: 'Peripheral was successfully created.' }
        format.json { render :show, status: :created, location: @peripheral }
      else
        format.html { render :new }
        format.json { render json: @peripheral.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peripherals/1
  # PATCH/PUT /peripherals/1.json
  def update
    respond_to do |format|
      if @peripheral.update(peripheral_params)
        format.html { redirect_to @peripheral, notice: 'Peripheral was successfully updated.' }
        format.json { render :show, status: :ok, location: @peripheral }
      else
        format.html { render :edit }
        format.json { render json: @peripheral.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peripherals/1
  # DELETE /peripherals/1.json
  def destroy
    @peripheral.destroy
    respond_to do |format|
      format.html { redirect_to peripherals_url, notice: 'Peripheral was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peripheral
      @peripheral = Peripheral.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peripheral_params
      params.require(:peripheral).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/employees_peripherals_helper.rb
module EmployeesPeripheralsHelper
end

app/helpers/peripherals_helper.rb
module PeripheralsHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
   
  <h2>Employee Peripherals</h2>
  <% Peripheral.all.each do |peripheral| %>
    <div>
      <%= check_box_tag :peripheral_ids, peripheral.id, @employee.peripherals.include?(peripheral), :name => 'employee[peripheral_ids][]' %>
      <%= label_tag :peripheral_ids, peripheral.name %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>
  <% @employee.peripherals.each do |ep| %>
    <%= ep.name %><br />
  <% end %>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/employees_peripherals/_form.html.erb
<%= form_for @employeesperipherals, as: :employeesperipherals, url: employees_peripherals_path do |f| %>
  <% if @employees_peripheral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employees_peripheral.errors.count, "error") %> prohibited this employees_peripheral from being saved:</h2>

      <ul>
      <% @employees_peripheral.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
     <%= f.label :employee_id %><br> 
     <%= collection_select(:employee_peripheral, :employee_id, Employee.all,
                  :id, :employee_name,
                 {:prompt => 'Please select the employee'}) %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees_peripherals/index.html.erb
<br> <%= link_to 'List Employee', peripherals_path %> <br><br>
<%= link_to 'List Peripherals', employees_path %><br>

<h1>Employees Peripherals</h1>

  <div class="field">
    <%= collection_select(:employee_peripheral, :employee_id, Employee.all,
                  :id, :name,
                 {:prompt => 'Please select the employee'}) %> <br>    
  </div>

<%= link_to 'submit', edit_employee_path() %>

<script type="text/javascript">
  var a =$('#employee_peripheral_employee_id').val()
</script>

app/views/employees_peripherals/new.html.erb
<%= form_for @employeesperipherals  do |f| %>


  <div class="field">
  <%= f.label :employee_id %>
    <%= collection_select(:employee_peripheral, :employee_id, Employee.all,
                  :id, :name,
                 {:prompt => 'Please select the employee'}),:id1 =>'employee_peripheral_employee_id' %> <br>     
  </div>
  <% end %>
<script type="text/javascript">
  var a =$('#employee_peripheral_employee_id').val()
</script>
<%= link_to 'Back', employees_path(:id1) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Accessoriesmanagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/peripherals/_form.html.erb
<%= form_for(@peripheral) do |f| %>
  <% if @peripheral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@peripheral.errors.count, "error") %> prohibited this peripheral from being saved:</h2>

      <ul>
      <% @peripheral.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/peripherals/edit.html.erb
<h1>Editing Peripheral</h1>

<%= render 'form' %>

<%= link_to 'Show', @peripheral %> |
<%= link_to 'Back', peripherals_path %>

app/views/peripherals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Peripherals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peripherals.each do |peripheral| %>
      <tr>
        <td><%= peripheral.name %></td>
        <td><%= link_to 'Show', peripheral %></td>
        <td><%= link_to 'Edit', edit_peripheral_path(peripheral) %></td>
        <td><%= link_to 'Destroy', peripheral, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peripheral', new_peripheral_path %>

app/views/peripherals/new.html.erb
<h1>New Peripheral</h1>

<%= render 'form' %>

<%= link_to 'Back', peripherals_path %>

app/views/peripherals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @peripheral.name %>
</p>

<%= link_to 'Edit', edit_peripheral_path(@peripheral) %> |
<%= link_to 'Back', peripherals_path %>